# Generated by Django 5.1 on 2025-04-16 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_extension', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
