# Generated by Django 5.1 on 2025-04-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community_extension', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='section',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('faculty', 'Faculty'), ('admin', 'Admin')], default='student', max_length=50),
        ),
    ]
